"""
Configuration file for DQ MDAR Masterfile Editor dropdown values.
Update the lists below to modify dropdown options.
"""

# Dropdown values for each field
DROPDOWN_VALUES = {
    "data_owner": [
        "Beverly Dolor",
        "Bert Lorica",
        "Jose Yulo",
        "Nitin Chawre",
        "Pat Hipol",
        "Javy Olives",
        "Proletaryo Cabales",
        "Camille Valmores",
        "Leo Capote",
        "Justin Dayrit",
        "Mike Favila",
        "Alvin Wong",
        "Mel Valerio",
        "Thai Dinh",
        "Ma. Cecilia Jimlan",
        "Michael Obaldo",
        "Addison Pelayo",
        "Bryan Judelle Ramos",
        "Steven Michael Reyes",
        "Abi Tabayoyong",
        "Pranay Chukkala",
        "Alvin Delagon",
        "Patrick Hipol",
        "Geraldine Veracion",
        "Lance Cham",
        "Donna Glaraga",
    ],
    
    "tech_group": [
        "DG",
        "PE02",
        "PE01",
        "PE03",
        "DE",
        "PO - Javy",
        "IDEA",
        "ISS",
        "EDS",
        "CrPM",
        "PO - Nitin",
        "PO - Bert",
        "PO - Cams",
        "Ops",
        "Fraud Analytics",
    ],
    
    "overall_status": [
        "Closed",
        "Open",
    ],
    
    "mdar_priority": [
        "High",
        "Low",
        "Medium",
    ],
    
    "root_cause_category": [
        "Data Inconsistency",
        "Source Issue",
        "Ingestion",
    ],
    
    "dq_poc": [
        "Gibe",
        "Roy",
        "Lors",
        "Rev",
        "Mar",
    ],
    
    "internal_domain": [
        "Lending",
        "Negosyo",
        "Consumer",
        "Transaction - Wallet",
        "Merchant",
        "Transaction - Bank",
        "Treasury",
        "Deposit",
    ],
    
    "internal_subdomain": [
        "Regulatory",
        "CPM",
        "BAU",
        "IDEA",
        "MDM",
        "CrPM",
        "CMS",
        "Lending",
        "FCI",
        "Crypto",
        "DS",
        "Cypto",
        "Escalated",
        "Financial",
        "Anomalo",
        "Finance",
    ],
    
    "mesh_team": [
        "Consumer Lending",
        "User Profiles",
        "Accounts Management",
        "Marketing Tech",
        "Enterprise Products Core",
        "Credit Infrastructure",
        "Business Deposits",
        "Cards Management",
        "Core Payment Platforms",
        "Partner Settlements",
        "Business Lending",
        "SKU Management",
        "Partner Cash Solutions",
        "Crypto",
        "Transaction Assets",
        "Salesforce",
        "Identity and Access Management",
        "Online Acceptance",
        "Core Platform Lending",
        "Open Loop Payment Channels",
        "Consumer Deposits",
        "Money Movement",
        "DE",
        "DG - MDM",
        "ISS",
        "EDG - DQ",
        "IDEA",
        "OPIC",
        "SSAP",
        "Self Top-up",
        "InterBank Transfers",
        "Risk Tech",
        "DG - Metadata",
        "Ops",
        "CBS Platform",
        "Business Manager",
        "Developer Experience",
        "Data Engineering",
        "Tech Ops",
        "Fraud",
        "Base App - Mobile",
        "E-Commerce",
        "Account Assets",
        "Closed Loop Payment Channels",
    ],
    
    "timeline_year": [
        "2026",
        "2027",
        "2028",
    ],
    
    "timeline_month": [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
    ],
    
    "timeline_quarter": [
        "Q1",
        "Q2",
        "Q3",
        "Q4",
    ],
}
